// lib/categorySchema.js

export const categories = [
  {
    key: 'c',
    label: 'Collections',
    icon: '📦',
    table: 'collections',
    select: 'id, name',
    orderBy: { column: 'created_at', ascending: false },
    formatLabel: rec => rec.name,
  },
  {
    key: 'd',
    label: 'Documents',
    icon: '📖',
    table: 'documents',
    select: 'id, name, description',
    orderBy: { column: 'created_at', ascending: false },
    formatLabel: rec => rec.description ? `${rec.name}, ${rec.description}` : rec.name,
  },
  {
    key: 'i',
    label: 'Items',
    icon: '📄',
    table: 'items',
    select: 'id, name',
    orderBy: { column: 'created_at', ascending: false },
    formatLabel: rec => rec.name,
  },
  {
    key: 'p',
    label: 'People',
    icon: '👤',
    table: 'people',
    select: 'id, name, aliases',
    orderBy: { column: 'name', ascending: true },
    formatLabel: rec => rec.aliases ? `${rec.name}, ${rec.aliases}` : rec.name,
},
  {
    key: 'g',
    label: 'Groups',
    icon: '👥',
    table: 'groups',
    select: 'id, name',
    orderBy: { column: 'created_at', ascending: false },
    formatLabel: rec => rec.name,
  },
  {
    key: 'l',
    label: 'Locations',
    icon: '📍',
    table: 'locations',
    select: 'id, name, country, lat, lng',
    formatLabel: rec => `${rec.name}, ${rec.country} (${rec.lat}, ${rec.lng})`,
  },
  {
    key: 'e',
    label: 'Events',
    icon: '📅',
    table: 'events',
    select: 'id, date',
    orderBy: { column: 'date', ascending: true },
    formatLabel: rec => new Date(rec.date).toLocaleDateString(),
  },
  {
    key: 't',
    label: 'Topics',
    icon: '🔖',
    table: 'topics',
    select: 'id, name',
    orderBy: { column: 'created_at', ascending: false },
    formatLabel: rec => rec.name,
  }
];
